import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {schedule} from '../desk/finance.js';
const db=new PGlite(),uid={admin:'00000000-0000-4000-a000-000000000001',officer:'00000000-0000-4000-a000-000000000002',cashier:'00000000-0000-4000-a000-000000000003',viewer:'00000000-0000-4000-a000-000000000004',stranger:'00000000-0000-4000-a000-000000000005'};
let count=0;
const q=(sql,p=[])=>db.query(sql,p),one=async(sql,p=[])=>{const r=await q(sql,p);return Object.values(r.rows[0])[0];};
async function rejected(fn,pattern){await assert.rejects(fn,pattern);count++;}
async function as(user,role='authenticated'){await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[user||'']);await db.exec('set role '+role);}
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
await db.exec(await readFile(new URL('../supabase/migrations/20261001075058_lending_v1.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261001084639_lending_indexes.sql',import.meta.url),'utf8'));
for(const [name,id] of Object.entries(uid)){await q('insert into auth.users values($1,$2)',[id,name+'@example.test']);if(name!=='stranger')await q('insert into public.staff_profiles(user_id,name,role) values($1,$2,$3)',[id,name,name==='officer'?'loan_officer':name==='admin'?'admin':name]);}
await as(uid.admin);
await rejected(()=>q('insert into public.borrowers(name,phone) values($1,$2)',['Bypass','+256700123456']),/permission denied/);
const data={name:'Fictional borrower',phone:'+256700123456',amount:100001,months:3,purpose:'Test business stock',consent:true},key='10000000-0000-4000-a000-000000000001';
let a=await one('select public.staff_application($1,$2)',[key,data]);
assert.equal((await one('select public.staff_application($1,$2)',[key,data])).id,a.id);count++;
await rejected(()=>q('select public.staff_application($1,$2)',[key,{...data,amount:99999}]),/different/);
await rejected(()=>q('select public.decide_application($1,true,100001,250,3,$2)',[a.id,'Verified documents']),/Confirm lending terms/);
await q('select public.save_lending_settings($1)',[{company:'Fodman test',min_amount:1,max_amount:100000000,rate_bps:250,max_months:12,terms_ready:true,two_person:false}]);
await as(uid.officer);await q('select public.review_application($1)',[a.id]);
await rejected(()=>q('select public.decide_application($1,true,100001,250,3,$2)',[a.id,'Verified documents']),/Permission denied/);
await as(uid.admin);await q('select public.decide_application($1,true,100001,250,3,$2)',[a.id,'Verified documents']);
const today=await one("select (now() at time zone 'Africa/Kampala')::date::text"),l=await one('select public.disburse_application($1,$2,$3,$4,true)',[a.id,today,'Cash','']);
assert.deepEqual(l.schedule,schedule(100001,250,3,today));count++;
assert.equal((await one('select public.disburse_application($1,$2,$3,$4,true)',[a.id,today,'Cash',''])).id,l.id);count++;
assert.equal(Number(await one('select count(*) from public.loans')),1);count++;
await rejected(()=>q('select public.disburse_application($1,$2,$3,$4,true)',[a.id,today,'MoMo','tx123']),/different/);
const payKey='20000000-0000-4000-a000-000000000001';
await as(uid.viewer);assert.equal((await one('select public.lending_snapshot()')).loans.length,1);count++;
await rejected(()=>q('select public.record_payment($1,$2,10000,$3,$4,$5)',[payKey,l.id,today,'Cash','']),/Permission denied/);
await as(uid.cashier);let p=await one('select public.record_payment($1,$2,10000,$3,$4,$5)',[payKey,l.id,today,'Cash','']);
assert.equal((await one('select public.record_payment($1,$2,10000,$3,$4,$5)',[payKey,l.id,today,'Cash',''])).id,p.id);count++;
assert.equal(Number(await one('select count(*) from public.payments')),1);count++;
await rejected(()=>q('select public.record_payment($1,$2,10001,$3,$4,$5)',[payKey,l.id,today,'Cash','']),/different/);
await rejected(()=>q('select public.reverse_payment($1,$2)',[p.id,'Wrong payment amount']),/Permission denied/);
await rejected(()=>q('select public.record_payment($1,$2,999999,$3,$4,$5)',['20000000-0000-4000-a000-000000000002',l.id,today,'Cash','']),/exceeds/);
const snapshot=await one('select public.lending_snapshot()');assert.equal(snapshot.loans[0].schedule[0].paid,10000);count++;
assert.equal(snapshot.audit.length,0);count++;
await as(uid.admin);await q('select public.reverse_payment($1,$2)',[p.id,'Entered against wrong receipt']);
assert.equal((await one('select public.lending_snapshot()')).loans[0].schedule[0].paid,0);count++;
assert.equal(Number(await one('select count(*) from public.payments')),1);count++;
await q('select public.record_payment($1,$2,107501,$3,$4,$5)',['20000000-0000-4000-a000-000000000003',l.id,today,'MoMo','MOMO123']);
const settled=await one('select public.lending_snapshot()');assert.equal(settled.loans[0].schedule.reduce((s,r)=>s+r.total-r.paid,0),0);count++;
await rejected(()=>q('select public.manage_staff($1,$2,false)',[uid.admin,'viewer']),/own administrator/);
await q('select public.manage_staff($1,$2,false)',[uid.viewer,'viewer']);await as(uid.viewer);
assert.equal(Number(await one('select count(*) from public.loans')),0);count++;
await rejected(()=>q('select public.lending_snapshot()'),/Permission denied/);
await as(uid.stranger);assert.equal(Number(await one('select count(*) from public.applications')),0);count++;
await rejected(()=>q('select public.lending_snapshot()'),/Permission denied/);
await as(null,'anon');await rejected(()=>q('select * from public.borrowers'),/permission denied/);
await rejected(()=>q('select public.website_application($1,$2,$3)',['30000000-0000-4000-a000-000000000001',data,'a'.repeat(64)]),/permission denied/);
await as(null,'service_role');const publicData={...data,name:'Website applicant',phone:'+256700999888'};
const webKey='30000000-0000-4000-a000-000000000001';const web=await one('select public.website_application($1,$2,$3)',[webKey,publicData,'a'.repeat(64)]);assert.deepEqual(Object.keys(web),['reference']);count++;
assert.deepEqual(await one('select public.website_application($1,$2,$3)',[webKey,publicData,'a'.repeat(64)]),web);count++;
await rejected(()=>q('select * from public.applications'),/permission denied/);
for(let i=2;i<=5;i++)await q('select public.website_application($1,$2,$3)',['30000000-0000-4000-a000-'+String(i).padStart(12,'0'),publicData,'a'.repeat(64)]);
await rejected(()=>q('select public.website_application($1,$2,$3)',['30000000-0000-4000-a000-000000000006',publicData,'a'.repeat(64)]),/Too many/);
await as(uid.admin);assert.equal((await one('select public.lending_snapshot()')).applications.filter(a=>a.source==='website').length,5);count++;
// Two-person policy is enforced by the database, not the browser.
await q('select public.save_lending_settings($1)',[{company:'Fodman test',min_amount:1,max_amount:100000000,rate_bps:250,max_months:12,terms_ready:true,two_person:true}]);
const a2=await one('select public.staff_application($1,$2)',['40000000-0000-4000-a000-000000000001',{...data,phone:'+256700777666'}]);
await q('select public.review_application($1)',[a2.id]);
await rejected(()=>q('select public.decide_application($1,true,100001,250,3,$2)',[a2.id,'Reviewed paperwork']),/different staff/);
await as(uid.officer);await q('select public.review_application($1)',[a2.id]);await as(uid.admin);await q('select public.decide_application($1,true,100001,250,3,$2)',[a2.id,'Reviewed paperwork']);count++;
await db.close();console.log(`PASS: ${count} database checks, including roles, duplicate retries, exact schedules, repayment reversal, settlement, public intake and two-person approval.`);
