import * as api from './api.js';
import {createDemo} from './demo.js';
import {schedule,loanFigures,businessDate} from './finance.js';
const cfg=window.FODMAN_CONFIG||{},app=document.querySelector('#app'),modal=document.querySelector('#modal');
let state=null,demo=null,page='overview',filter='',statusFilter='',lastSync=null,syncError='',busy=false,poller=null;
const money=n=>'UGX '+Number(n||0).toLocaleString('en-US');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?new Date(s.length===10?s+'T00:00:00Z':s).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'Africa/Kampala'}):'—';
const roles={admin:'Administrator',loan_officer:'Loan officer',cashier:'Cashier',viewer:'Viewer'};
const can=r=>state&&r.includes(state.profile.role);
const borrower=id=>state.borrowers.find(b=>b.id===id)||{name:'Unknown borrower',phone:''};
const loan=id=>state.loans.find(l=>l.id===id);
const icon=(name)=>{const shapes={overview:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',applications:'<path d="M8 3h8l4 4v14H4V3h4zM14 3v5h6M8 12h8M8 16h6"/>',borrowers:'<circle cx="10" cy="8" r="4"/><path d="M2 21v-2a7 7 0 0 1 14 0v2M17 4a4 4 0 0 1 0 8M18 16a5 5 0 0 1 4 5"/>',loans:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h4"/>',payments:'<path d="M4 9h16M16 5l4 4-4 4M20 17H4M8 13l-4 4 4 4"/>',reports:'<path d="M4 3v18h17M8 16v-5M13 16V6M18 16v-8"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${shapes[name]||shapes.overview}</svg>`;};
const badge=s=>`<span class="badge ${['Approved','Active','Cleared','Disbursed'].includes(s)?'green':['Overdue','Rejected','Reversed'].includes(s)?'red':s==='Under review'?'gold':''}">${esc(s)}</span>`;
const button=(label,action,id='',style='secondary small')=>`<button class="btn ${style}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
function notice(s){const n=document.querySelector('#notice');n.textContent=s;n.classList.add('visible');setTimeout(()=>n.classList.remove('visible'),5000);}
function field(label,name,value='',extra='',type='text'){return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(label,name,options,value=''){return `<label class="field">${label}<select name="${name}">${options.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`;}).join('')}</select></label>`;}
function openModal(title,body){document.querySelector('#modalBody').innerHTML=`<div class="modal-head"><h2>${esc(title)}</h2><button class="close" data-action="close" aria-label="Close dialog">×</button></div><div class="modal-content">${body}</div>`;if(!modal.open)modal.showModal();}
const errorBox='<div class="error" role="alert" data-error></div>';
const formEnd=label=>`${errorBox}<div class="actions"><button type="button" class="btn secondary" data-action="close">Cancel</button><button class="btn" type="submit">${label}</button></div></form>`;
function login(){
  const ready=api.configured()&&!location.hostname.endsWith('github.io');
  app.innerHTML=`<main class="login" id="content"><section class="login-story"><div class="brand"><img src="../assets/fodman-mark.png" alt=""><div>FODMAN<i>.</i><small>INTERNATIONAL</small></div></div><div><div class="eyebrow">Lending desk · V1</div><h1>Clear decisions.<br>Stronger relationships.</h1><p>One place to manage applications, loans and repayments. Built around your lending desk.</p></div><small style="color:#bbaacb">Finance · Trust · Growth</small></section><section class="login-panel"><div class="login-card"><div class="eyebrow">Welcome back</div><h2>Your lending desk.</h2><p class="muted">Sign in to your authorised staff account.</p>${ready?`<form id="signin">${field('Email address','email','','autocomplete="username" required','email')}${field('Password','password','','autocomplete="current-password" required','password')}${errorBox}<button class="btn full" type="submit">Sign in →</button></form><button class="link" style="margin-top:12px" data-action="forgot">Forgot password?</button>`:`<div class="callout">Live access is being set up. You can explore V1 using fictional data below.</div>`}<div class="divider">Preview the software</div><button class="btn secondary full" data-action="demo">Open demonstration →</button><p class="privacy-note">The demonstration uses fictional records. It never connects to the live database.</p><p class="privacy-note"><a href="${esc(cfg.websiteUrl||'../index.html')}">← Return to Fodman website</a></p></div></section></main>`;
}
async function sync(render=true){
  if(!state&&!api.restore()&&!demo)return;
  try{state=demo?demo.snapshot():await api.rpc('lending_snapshot');lastSync=new Date();syncError='';if(render&&!modal.open)draw();}
  catch(e){syncError=e.message;if(render){if(state)draw();else {login();notice(e.message);}}}
}
async function call(name,args){if(!demo&&syncError)throw Error('Refresh the connection before making changes.');return demo?demo.rpc(name,args):api.rpc(name,args);}
function draw(){
  if(!state)return login();
  const tabs={overview:'Overview',applications:'Applications',borrowers:'Borrowers',loans:'Loans',payments:'Repayments',reports:'Reports',settings:can(['admin'])?'Team & settings':'My account'};
  app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="../assets/fodman-mark.png" alt=""><div>FODMAN<i>.</i><small>LENDING DESK</small></div></div><nav aria-label="Lending desk">${Object.entries(tabs).map(([id,name])=>`<button class="nav-item ${page===id?'active':''}" data-page="${id}" ${page===id?'aria-current="page"':''}>${icon(id)}${name}</button>`).join('')}</nav><div class="sidebar-bottom"><a href="${esc(cfg.websiteUrl||'../index.html')}" target="_blank" rel="noopener">↗ Company website</a><div class="profile"><span class="avatar">${esc(state.profile.name.slice(0,1))}</span><div>${esc(state.profile.name)}<br><small>${roles[state.profile.role]}</small></div></div></div></aside><div class="workspace">${demo?`<div class="demo-banner"><span><b>DEMONSTRATION</b> · Fictional records. Changes stay in this tab.</span><button data-action="resetdemo">Reset demo</button></div>`:''}${syncError?`<div class="sync-error" role="alert">Could not refresh: ${esc(syncError)}. Last confirmed records shown. Changes are paused.</div>`:''}<header class="topbar"><div style="display:flex;align-items:center;gap:15px"><button class="mobile-toggle" data-action="menu" aria-label="Open navigation">☰</button><div class="crumb">Workspace <strong>/ ${tabs[page]}</strong></div></div><div class="top-actions"><span class="top-status"><span class="status-dot" style="${syncError?'background:#b13647':''}"></span>${demo?'Demo mode':lastSync?'Updated '+lastSync.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'Connecting'}</span>${button('Refresh','refresh')}${button(demo?'Exit demo':'Sign out','logout')}</div></header><main class="content" id="content">${views[page]()}</main></div></div>`;
}
function heading(title,sub,action=''){return `<div class="page-head"><div><div class="eyebrow">Fodman lending</div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;}
function metric(label,value,note){return `<div class="metric"><div class="metric-label">${label}</div><b class="num">${value}</b><small>${note}</small></div>`;}
function table(headers,rows,empty='No records yet.'){return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`:`<div class="empty"><strong>${empty}</strong>Records will appear here after they are saved.</div>`;}
function filters(options=[]){return `<div class="filters"><input id="search" aria-label="Search records" placeholder="Search name, phone or reference…" value="${esc(filter)}">${options.length?`<select id="statusFilter" aria-label="Filter by status"><option value="">All statuses</option>${options.map(s=>`<option ${statusFilter===s?'selected':''}>${s}</option>`).join('')}</select>`:''}<span class="search-note">Whole amounts in Ugandan shillings</span></div>`;}
const matches=(...parts)=>parts.join(' ').toLowerCase().includes(filter.toLowerCase());
function applicationRows(list){return list.map(a=>`<tr><td><button class="table-link" data-action="application" data-id="${a.id}">${esc(a.name)}</button><small>${esc(a.reference)}</small></td><td>${money(a.amount)}<small>${a.months} months requested</small></td><td>${badge(a.status)}</td><td>${esc(a.source==='website'?'Website':'Staff desk')}<small>${date(a.created_at)}</small></td><td>${button('Open','application',a.id)}</td></tr>`);}
const views={
 overview(){
  const figures=state.loans.map(l=>loanFigures(l)),sum=k=>figures.reduce((s,f)=>s+f[k],0),open=state.applications.filter(a=>['New','Under review'].includes(a.status)),active=figures.filter(f=>f.balance>0).length;
  const todayPaid=state.payments.filter(p=>!p.voided_at&&p.paid_on===businessDate()).reduce((s,p)=>s+p.amount,0);
  const overdue=state.loans.filter(l=>loanFigures(l).overdue>0);
  return heading('Your desk, at a glance.','Applications to action. Repayments to follow up.',can(['admin','loan_officer'])?button('+ New application','newapp','',''): '')+(!state.settings.terms_ready?'<div class="callout warning">Confirm the company’s loan terms in Team & settings before approving loans.</div>':'')+`<div class="metrics">${metric('Portfolio outstanding',money(sum('balance')),active+' active loans · principal + interest')}${metric('Collected today',money(todayPaid),'Confirmed repayments · Kampala date')}${metric('Awaiting a decision',open.length,'New and reviewed applications')}${metric('Overdue instalments',money(sum('overdue')),overdue.length+' loans needing follow-up')}</div><div class="panels"><div><section class="card"><div class="card-head"><div><h2>Applications to action</h2><p>Requests awaiting review or approval</p></div><button class="link" data-page="applications">View all →</button></div>${table(['Applicant','Requested','Status','Source',''],applicationRows(open.slice(0,5)),'Your application queue is clear.')}</section><section class="card"><div class="card-head"><div><h2>Repayment follow-up</h2><p>Unpaid instalments before today</p></div><button class="link" data-page="loans">View loans →</button></div>${table(['Borrower','Overdue','Outstanding',''],overdue.slice(0,4).map(l=>{const b=borrower(l.borrower_id),f=loanFigures(l);return `<tr><td>${esc(b.name)}<small>${esc(b.phone)}</small></td><td>${money(f.overdue)}</td><td>${money(f.balance)}</td><td>${button('Open','loan',l.id)}</td></tr>`;}),'No overdue instalments.')}</section></div><aside><section class="card"><div class="card-head"><div><h2>Application pipeline</h2><p>From first request to disbursement</p></div></div><div class="card-body">${['New','Under review','Approved','Disbursed'].map(s=>`<div class="stage"><div class="stage-count">${state.applications.filter(a=>a.status===s).length}</div><span>${s}</span>${s==='Approved'?'<small>Ready for funds</small>':''}</div>`).join('')}</div></section><section class="card"><div class="card-head"><h2>Today’s priorities</h2></div><div class="card-body"><p class="settings-copy">${open.length?`Review ${open.length} application${open.length===1?'':'s'} and confirm the borrower’s documents.`:'Your application queue is up to date.'}</p><p class="settings-copy">${overdue.length?`Follow up ${overdue.length} overdue loan${overdue.length===1?'':'s'} with a reviewed reminder.`:'Keep the receipt record up to date after each repayment.'}</p>${button('Record a repayment','newpayment','','full')}</div></section><p class="privacy-note">Repayments are recorded after funds are received. MoMo and bank transfers are confirmed manually in V1.</p></aside></div>`;
 },
 applications(){const list=state.applications.filter(a=>matches(a.name,a.phone,a.reference)&&(!statusFilter||a.status===statusFilter));return heading('Applications','Website and staff requests in one shared queue.',can(['admin','loan_officer'])?button('+ New application','newapp','',''): '')+filters(['New','Under review','Approved','Rejected','Disbursed'])+`<section class="card">${table(['Applicant','Requested','Status','Source',''],applicationRows(list))}</section>`;},
 borrowers(){return heading('Borrowers','Borrower records created when an approved loan is disbursed.')+filters()+`<section class="card">${table(['Borrower','Phone','Loans','Outstanding',''],state.borrowers.filter(b=>matches(b.name,b.phone)).map(b=>{const list=state.loans.filter(l=>l.borrower_id===b.id),balance=list.reduce((s,l)=>s+loanFigures(l).balance,0);return `<tr><td><b>${esc(b.name)}</b><small>${esc(b.address||'Address not supplied')}</small></td><td>${esc(b.phone)}</td><td>${list.length}</td><td>${money(balance)}</td><td>${button('View loans','borrower',b.id)}</td></tr>`;}))}</section>`;},
 loans(){const list=state.loans.filter(l=>{const b=borrower(l.borrower_id),f=loanFigures(l);return matches(b.name,b.phone,l.reference)&&(!statusFilter||statusFilter===f.status);});return heading('Loan portfolio','Confirmed disbursements and their repayment schedules.')+filters(['Active','Overdue','Cleared'])+`<section class="card">${table(['Borrower / loan','Principal','Outstanding','Next instalment','Status',''],list.map(l=>{const b=borrower(l.borrower_id),f=loanFigures(l);return `<tr><td><button class="table-link" data-action="loan" data-id="${l.id}">${esc(b.name)}</button><small>${esc(l.reference)}</small></td><td>${money(l.principal)}<small>${l.rate_bps/100}% flat per month</small></td><td>${money(f.balance)}<small>${money(f.paid)} collected</small></td><td>${f.next?date(f.next.due_date):'Complete'}</td><td>${badge(f.status)}</td><td>${button('Open','loan',l.id)}</td></tr>`;}))}</section>`;},
 payments(){return heading('Repayments','Every payment keeps a receipt and audit trail.',can(['admin','cashier'])?button('+ Record repayment','newpayment','',''): '')+filters()+`<section class="card">${table(['Receipt / borrower','Amount','Method','Received','Status',''],state.payments.filter(p=>matches(p.reference,p.external_ref,borrower(loan(p.loan_id)?.borrower_id).name)).map(p=>{const l=loan(p.loan_id),b=borrower(l?.borrower_id);return `<tr><td><button class="table-link" data-action="receipt" data-id="${p.id}">${esc(p.reference)}</button><small>${esc(b.name)}</small></td><td>${money(p.amount)}</td><td>${esc(p.method)}<small>${esc(p.external_ref||'Cash receipt')}</small></td><td>${date(p.paid_on)}</td><td>${badge(p.voided_at?'Reversed':'Recorded')}</td><td>${button('Receipt','receipt',p.id)}</td></tr>`;}))}</section>`;},
 reports(){const fs=state.loans.map(l=>loanFigures(l)),sum=k=>fs.reduce((s,f)=>s+f[k],0),payments=state.payments.filter(p=>!p.voided_at),collected=payments.reduce((s,p)=>s+p.amount,0),principal=state.loans.reduce((s,l)=>s+l.principal,0);return heading('Reports & records','Portfolio totals reconcile with confirmed transactions.',button('Export CSV','exportcsv','',''))+`<div class="metrics">${metric('Total receivable',money(sum('total')),'Principal + contracted flat interest')}${metric('Total collected',money(collected),'Excludes reversed payments')}${metric('Outstanding',money(sum('balance')),'Receivable minus collected')}${metric('Principal disbursed',money(principal),'Total funds issued')}</div><div class="two-col"><section class="card"><div class="card-head"><h2>Repayments by method</h2></div><div class="card-body">${['Cash','MoMo','Bank'].map(m=>`<div class="statline"><span>${m}</span><b>${money(payments.filter(p=>p.method===m).reduce((s,p)=>s+p.amount,0))}</b></div>`).join('')}<div class="callout ${collected===sum('paid')?'':'warning'}">${collected===sum('paid')?'Reconciled: receipts equal repayment allocations.':'Reconciliation difference detected. Review records before continuing.'}</div><p class="settings-copy">V1 reports track loan principal, contracted interest and collected repayments. They are an operational record; expense accounting and profit reports are outside this release.</p></div></section><section class="card"><div class="card-head"><h2>Backup & export</h2></div><div class="card-body"><p class="settings-copy">Download a dated copy of the confirmed lending records. Store it securely. Exports contain personal and financial information.</p>${button('Download records (JSON)','backup','','')}<p class="settings-copy">JSON is a records export. Restoration requires administrator review and a controlled import; uploading a backup is not enabled in V1.</p><p class="privacy-note">Last refresh: ${date(state.server_time)} · ${demo?'demonstration only':'shared database records'}</p></div></section></div>${can(['admin'])?`<section class="card"><div class="card-head"><h2>Recent audit history</h2><small>Latest 100 events</small></div>${table(['When','Action','Actor','Record'],state.audit.map(a=>`<tr><td>${date(a.created_at)}</td><td>${esc(a.action.replaceAll('_',' '))}</td><td>${esc(state.staff.find(s=>s.user_id===a.actor_id)?.name||'Website / system')}</td><td><small>${esc(a.entity_id)}</small></td></tr>`),'No audit events yet.')}</section>`:''}`;},
 settings(){const s=state.settings;return heading(can(['admin'])?'Team & settings':'My account','Control access and confirm the terms used by your lending desk.')+`<section class="card"><div class="card-head"><h2>Your account</h2></div><div class="card-body"><div class="detail-grid"><div><small>Name</small><b>${esc(state.profile.name)}</b></div><div><small>Access</small><b>${roles[state.profile.role]}</b></div></div>${!demo?button('Change password','password','',''):''}</div></section>`+(can(['admin'])?`<div class="two-col"><section class="card"><div class="card-head"><h2>Lending terms</h2>${badge(s.terms_ready?'Confirmed':'Draft')}</div><div class="card-body">${demo?'<div class="callout warning">These rates are fictional examples for demonstration.</div>':''}<form id="settings">${field('Company name','company',s.company,'required maxlength="160"')}<div class="form-grid">${field('Minimum loan (UGX)','min_amount',s.min_amount,'required min="1" max="1000000000" step="1"','number')}${field('Maximum loan (UGX)','max_amount',s.max_amount,'required min="1" max="1000000000" step="1"','number')}${field('Default flat monthly interest (%)','rate',s.rate_bps==null?'':s.rate_bps/100,'required min="0" max="100" step="0.01"','number')}${field('Maximum term (months)','max_months',s.max_months,'required min="1" max="60" step="1"','number')}</div><p class="settings-copy">V1 uses flat interest per month, monthly instalments and whole UGX. Approved loans keep their original terms when settings change.</p><label class="check"><input type="checkbox" name="two_person" ${s.two_person?'checked':''}><span>Require review by a different staff member before approval. Add another reviewer before enabling this.</span></label><label class="check"><input type="checkbox" name="confirmed" required><span>I confirm these are the company’s agreed lending terms.</span></label>${errorBox}<button class="btn" type="submit">Save confirmed terms</button></form></div></section><section class="card"><div class="card-head"><div><h2>Staff access</h2><p>Francis can add users when the team grows.</p></div>${button('+ Add user','invite')}</div>${table(['Staff member','Role','Access',''],state.staff.map(x=>`<tr><td><b>${esc(x.name)}</b><small>${esc(x.email||'')}</small></td><td>${roles[x.role]}</td><td>${badge(x.active?'Active':'Disabled')}</td><td>${x.user_id!==state.profile.user_id?button('Manage','staff',x.user_id):'<small>You</small>'}</td></tr>`))}<div class="card-body"><p class="settings-copy"><b>Administrator:</b> approval, disbursement, repayments, settings and staff.<br><b>Loan officer:</b> applications and reviews.<br><b>Cashier:</b> repayments and receipts.<br><b>Viewer:</b> records and reports.</p></div></section></div>`:'');}
};
function newApplication(){openModal('New application',`<form id="newapp" data-key="${crypto.randomUUID()}"><div class="form-grid">${field('Full name','name','','required minlength="2" maxlength="160" autocomplete="name"')}${field('Phone / WhatsApp','phone','','required maxlength="22" placeholder="+256…"','tel')}${field('Requested amount (UGX)','amount','','required min="1" max="1000000000" step="1"','number')}${field('Preferred term (months)','months','','required min="1" max="60" step="1"','number')}<label class="field span">Purpose<textarea name="purpose" required minlength="2" maxlength="1000"></textarea></label>${field('Address (optional)','address','','maxlength="500"')}</div><label class="check"><input name="consent" type="checkbox" required><span>The applicant has agreed to Fodman contacting them and recording this request.</span></label>${formEnd('Save application')}`);}
function openApplication(id){const a=state.applications.find(a=>a.id===id);if(!a)return;openModal(a.reference,`<h2>${esc(a.name)}</h2><p class="muted">${esc(a.phone)} · ${badge(a.status)}</p><div class="detail-grid"><div><small>Requested</small><b>${money(a.amount)}</b></div><div><small>Preferred term</small><b>${a.months} months</b></div><div><small>Source</small><b>${a.source==='website'?'Website':'Staff desk'}</b></div><div><small>Received</small><b>${date(a.created_at)}</b></div></div><p class="settings-copy"><b>Purpose:</b> ${esc(a.purpose)}</p>${a.decision_note?`<p class="settings-copy"><b>Decision:</b> ${esc(a.decision_note)}</p>`:''}${a.status==='Approved'?`<div class="terms-summary">Approved principal: <strong>${money(a.approved_principal)}</strong><br>Monthly flat interest: <strong>${a.approved_rate_bps/100}%</strong><br>Term: <strong>${a.approved_months} months</strong></div>`:''}${errorBox}<div class="actions">${['New','Under review'].includes(a.status)&&can(['admin','loan_officer'])?button('Mark reviewed','review',a.id):''}${['New','Under review'].includes(a.status)&&can(['admin'])?button('Reject','reject',a.id,'danger')+button('Approve terms','approve',a.id,''):''}${a.status==='Approved'&&can(['admin'])?button('Record disbursement','disburse',a.id,''):''}${a.status==='Disbursed'?button('Open loan','loan',state.loans.find(l=>l.application_id===a.id)?.id,''):''}</div>`);}
function decide(id,approve){const a=state.applications.find(a=>a.id===id),s=state.settings;if(approve&&!s.terms_ready){notice('Confirm lending terms in Settings first.');return;}openModal(approve?'Approve loan terms':'Reject application',`<form id="decision" data-id="${id}" data-approve="${approve}"><p class="settings-copy">${esc(a.name)} · ${money(a.amount)} requested</p>${approve?`<div class="form-grid">${field('Approved principal (UGX)','principal',a.amount,`required min="${s.min_amount}" max="${s.max_amount}" step="1"`,'number')}${field('Monthly flat interest (%)','rate',s.rate_bps/100,'required min="0" max="100" step="0.01"','number')}${field('Approved term (months)','months',Math.min(a.months,s.max_months),`required min="1" max="${s.max_months}" step="1"`,'number')}</div><div class="terms-summary" id="quote"></div><label class="check"><input type="checkbox" name="verified" required><span>I have assessed the borrower, checked the required documents and confirmed these terms.</span></label>`:''}<label class="field">Decision note<textarea name="note" required minlength="5" maxlength="2000" placeholder="Record the assessment and decision…"></textarea></label>${formEnd(approve?'Approve application':'Reject application')}`);if(approve)updateQuote();}
function updateQuote(){const f=document.querySelector('#decision');if(!f)return;try{const p=Number(f.principal.value),r=Math.round(Number(f.rate.value)*100),n=Number(f.months.value),rows=schedule(p,r,n,businessDate()),total=rows.reduce((s,r)=>s+r.total,0);document.querySelector('#quote').innerHTML=`Total repayment: <strong>${money(total)}</strong><br>Total flat interest: <strong>${money(total-p)}</strong><br>Monthly instalment: <strong>${money(rows[0].total)}</strong>${rows.at(-1).total!==rows[0].total?` · final ${money(rows.at(-1).total)}`:''}`;}catch{document.querySelector('#quote').textContent='Enter valid terms to preview repayment.';}}
function disbursement(id){const a=state.applications.find(a=>a.id===id);openModal('Record disbursement',`<form id="disburse" data-id="${id}"><p class="settings-copy">${esc(a.name)} · approved principal ${money(a.approved_principal)}</p><div class="callout">Record this only after the loan agreement is signed and funds have been sent. This action creates the loan and its repayment schedule.</div><div class="form-grid">${field('Funds sent on','date',businessDate(),`required max="${businessDate()}" min="${a.approved_at?.slice(0,10)||businessDate()}"`,'date')}${select('Method','method',['Cash','MoMo','Bank'])}${field('Transaction reference','ref','','maxlength="120" placeholder="Required for MoMo / Bank"')}</div><label class="check"><input type="checkbox" name="agreement" required><span>The agreement is signed and ${money(a.approved_principal)} has been disbursed.</span></label>${formEnd('Confirm disbursement')}`);}
function openLoan(id){const l=loan(id);if(!l)return;const b=borrower(l.borrower_id),f=loanFigures(l);openModal(l.reference,`<h2>${esc(b.name)}</h2><p class="muted">${esc(b.phone)} · ${badge(f.status)}</p><div class="detail-grid"><div><small>Principal issued</small><b>${money(l.principal)}</b></div><div><small>Outstanding</small><b>${money(f.balance)}</b></div><div><small>Terms</small><b>${l.rate_bps/100}% flat / month · ${l.months} months</b></div><div><small>Disbursed</small><b>${date(l.disbursed_on)} · ${esc(l.disbursement_method||'Cash')}</b></div></div>${table(['Instalment','Due','Amount','Paid','Balance'],l.schedule.map(r=>`<tr><td>${r.n}</td><td>${date(r.due_date)}</td><td>${money(r.total)}</td><td>${money(r.paid)}</td><td>${money(r.total-r.paid)}</td></tr>`))}<div class="actions">${button('Print statement','print')}${f.overdue>0&&can(['admin','loan_officer'])?button('Review reminder','reminder',l.id):''}${f.balance>0&&can(['admin','cashier'])?button('Record repayment','newpayment',l.id,''):''}</div>`);}
function paymentForm(id=''){if(!can(['admin','cashier'])){notice('Only the administrator or cashier can record repayments.');return;}const list=state.loans.filter(l=>loanFigures(l).balance>0);if(!list.length){notice('No loans have an outstanding balance.');return;}openModal('Record repayment',`<form id="payment" data-key="${crypto.randomUUID()}">${select('Loan','loan',list.map(l=>[l.id,borrower(l.borrower_id).name+' · '+l.reference+' · '+money(loanFigures(l).balance)]),id||list[0].id)}<div class="form-grid">${field('Amount received (UGX)','amount','','required min="1" step="1" max="100000000000"','number')}${field('Received on','date',businessDate(),`required max="${businessDate()}"`,'date')}${select('Method','method',['Cash','MoMo','Bank'])}${field('Transaction reference','ref','','maxlength="120" placeholder="Required for MoMo / Bank"')}</div><label class="check"><input type="checkbox" required name="received"><span>I have confirmed these funds were received.</span></label><p class="settings-copy">The payment is applied to the oldest unpaid instalment first. A confirmed receipt appears after the server saves it.</p>${formEnd('Save repayment & receipt')}`);}
function receipt(id){const p=state.payments.find(p=>p.id===id),l=loan(p?.loan_id);if(!p||!l)return;const b=borrower(l.borrower_id);openModal(p.reference,`<div class="receipt-head"><div class="eyebrow">${demo?'DEMONSTRATION · ':''}Fodman lending</div><h2>${esc(state.settings.company)}</h2><p class="settings-copy">Repayment receipt · ${esc(p.reference)}</p>${p.voided_at?badge('Reversed'):badge('Recorded')}</div><div class="receipt-total">${money(p.amount)}</div><div class="detail-grid"><div><small>Received from</small><b>${esc(b.name)}</b></div><div><small>Loan</small><b>${esc(l.reference)}</b></div><div><small>Payment date</small><b>${date(p.paid_on)}</b></div><div><small>Method / reference</small><b>${esc(p.method)} · ${esc(p.external_ref||'Cash')}</b></div><div><small>Recorded by</small><b>${esc(state.staff.find(s=>s.user_id===p.recorded_by)?.name||state.profile.name)}</b></div><div><small>Loan balance at statement time</small><b>${money(loanFigures(l).balance)}</b></div></div>${p.voided_at?`<div class="callout warning">Reversed on ${date(p.voided_at)}. Reason: ${esc(p.void_reason)}. This receipt no longer counts toward the loan.</div>`:''}<p class="privacy-note">This receipt records funds received. The balance shown reflects all currently confirmed transactions, including later repayments.</p><div class="actions">${can(['admin'])&&!p.voided_at?button('Reverse entry','reverse',p.id,'danger'):''}${button('Print / save PDF','print','','')}</div>`);}
function download(name,contents,type){const url=URL.createObjectURL(new Blob([contents],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function csv(){const rows=[['Loan','Borrower','Phone','Principal_UGX','Monthly_flat_rate_percent','Term_months','Disbursed_on','Total_UGX','Paid_UGX','Balance_UGX','Overdue_UGX','Status'],...state.loans.map(l=>{const b=borrower(l.borrower_id),f=loanFigures(l);return[l.reference,b.name,b.phone,l.principal,l.rate_bps/100,l.months,l.disbursed_on,f.total,f.paid,f.balance,f.overdue,f.status];})];const cell=x=>{let s=String(x??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};download((demo?'DEMO-':'')+'FODMAN-portfolio-'+businessDate()+'.csv','\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');notice('Portfolio exported. Store the file securely.');}
document.addEventListener('click',async e=>{
 const btn=e.target.closest('[data-page],[data-action]');if(!btn||busy)return;
 if(btn.dataset.page){page=btn.dataset.page;filter='';statusFilter='';draw();return;}
 const action=btn.dataset.action,id=btn.dataset.id;
 try{
  if(action==='close')modal.close();
  if(action==='menu')document.querySelector('.sidebar').classList.toggle('open');
  if(action==='demo'||action==='resetdemo'){demo=createDemo();state=demo.snapshot();page='overview';filter='';statusFilter='';syncError='';lastSync=new Date();modal.close();draw();}
  if(action==='refresh')await sync();
  if(action==='logout'){clearInterval(poller);poller=null;modal.close();await api.signOut();state=null;demo=null;login();}
  if(action==='newapp')newApplication();
  if(action==='application')openApplication(id);
  if(action==='review'){busy=true;btn.disabled=true;await call('review_application',{p_id:id});await sync(false);openApplication(id);draw();notice('Application marked reviewed.');}
  if(action==='approve'||action==='reject')decide(id,action==='approve');
  if(action==='disburse')disbursement(id);
  if(action==='loan')openLoan(id);
  if(action==='borrower'){page='loans';filter=borrower(id).phone;statusFilter='';draw();}
  if(action==='newpayment')paymentForm(id);
  if(action==='receipt')receipt(id);
  if(action==='print')window.print();
  if(action==='reverse'){openModal('Reverse repayment',`<form id="reverse" data-id="${id}"><div class="callout warning">The original receipt remains in the record, marked reversed. Its amount is removed from the repayment allocation.</div><label class="field">Reason for reversal<textarea name="reason" required minlength="8" maxlength="2000"></textarea></label>${formEnd('Confirm reversal')}`);}
  if(action==='reminder'){const l=loan(id),b=borrower(l.borrower_id),f=loanFigures(l),msg=`Hello ${b.name}, this is Fodman. Our records show ${money(f.overdue)} overdue on loan ${l.reference}. Please contact us to confirm your repayment arrangements. If you have already paid, share the transaction reference so we can check. Thank you.`;openModal('Review repayment reminder',`<p class="settings-copy">Review the message, then send it yourself in WhatsApp.</p><label class="field">Prepared message<textarea id="reminderText" rows="6">${esc(msg)}</textarea></label><div class="actions">${button('Open WhatsApp draft','whatsapp',l.id,'')}</div>`);}
  if(action==='whatsapp'){const l=loan(id),b=borrower(l.borrower_id),msg=document.querySelector('#reminderText').value;window.open('https://wa.me/'+b.phone.replace(/\D/g,'')+'?text='+encodeURIComponent(msg),'_blank','noopener');}
  if(action==='backup'){download((demo?'DEMO-':'')+'FODMAN-records-'+businessDate()+'.json',JSON.stringify({version:1,mode:demo?'demo':'live',exported_at:new Date().toISOString(),...state},null,2),'application/json');notice('Confirmed records exported.');}
  if(action==='exportcsv')csv();
  if(action==='invite'){if(demo){notice('User invitations are available after live setup.');return;}openModal('Add staff user',`<form id="invite">${field('Full name','name','','required maxlength="120"')}${field('Email address','email','','required','email')}${select('Role','role',Object.entries(roles),'viewer')}<p class="settings-copy">This sends an account invitation to the entered email address. Check the recipient carefully.</p>${formEnd('Send invitation')}`);}
  if(action==='staff'){const s=state.staff.find(s=>s.user_id===id);openModal('Manage '+s.name,`<form id="staff" data-id="${id}">${select('Role','role',Object.entries(roles),s.role)}<label class="check"><input type="checkbox" name="active" ${s.active?'checked':''}><span>Active account</span></label>${formEnd('Save access')}`);}
  if(action==='password')passwordForm();
  if(action==='forgot'){openModal('Reset password',`<form id="recover">${field('Account email address','email','','required autocomplete="email"','email')}${formEnd('Send reset email')}`);}
 }catch(err){const box=modal.open?modal.querySelector('[data-error]'):null;if(box)box.textContent=err.message;else notice(err.message);}finally{busy=false;btn.disabled=false;}
});
function passwordForm(){openModal('Set your password',`<form id="password">${field('New password','password','','required minlength="12" autocomplete="new-password"','password')}${field('Confirm new password','confirm','','required minlength="12" autocomplete="new-password"','password')}${formEnd('Save password')}`);}
document.addEventListener('input',e=>{if(e.target.closest('#decision'))updateQuote();if(e.target.id==='search'){const pos=e.target.selectionStart;filter=e.target.value;draw();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{if(e.target.id==='statusFilter'){statusFilter=e.target.value;draw();}});
document.addEventListener('submit',async e=>{
 const f=e.target;if(!f.matches('form'))return;e.preventDefault();if(busy||!f.reportValidity())return;
 const box=f.querySelector('[data-error]');if(box)box.textContent='';busy=true;f.querySelectorAll('button').forEach(b=>b.disabled=true);
 const data=new FormData(f),get=n=>String(data.get(n)||''),num=n=>Number(get(n));
 try{
  if(f.id==='signin'){await api.signIn(get('email').trim(),get('password'));await sync(false);if(!state)throw Error(syncError||'Could not load staff account.');draw();startPolling();return;}
  if(f.id==='recover'){await api.recover(get('email').trim());modal.close();notice('If the account exists, a reset email has been requested.');return;}
  if(f.id==='password'){if(get('password')!==get('confirm'))throw Error('Passwords do not match.');await api.changePassword(get('password'));modal.close();notice('Password updated.');return;}
  if(f.id==='newapp'){await call('staff_application',{p_key:f.dataset.key,p_data:{name:get('name').trim(),phone:get('phone').replace(/[ ()-]/g,''),amount:num('amount'),months:num('months'),purpose:get('purpose').trim(),address:get('address').trim(),consent:get('consent')==='on'}});}
  if(f.id==='decision'){await call('decide_application',{p_id:f.dataset.id,p_approve:f.dataset.approve==='true',p_principal:num('principal')||null,p_rate_bps:f.dataset.approve==='true'?Math.round(num('rate')*100):null,p_months:num('months')||null,p_note:get('note').trim()});}
  if(f.id==='disburse'){await call('disburse_application',{p_id:f.dataset.id,p_date:get('date'),p_method:get('method'),p_ref:get('ref').trim(),p_agreement:get('agreement')==='on'});}
  let saved;
  if(f.id==='payment'){saved=await call('record_payment',{p_key:f.dataset.key,p_loan:get('loan'),p_amount:num('amount'),p_date:get('date'),p_method:get('method'),p_ref:get('ref').trim()});}
  if(f.id==='reverse'){await call('reverse_payment',{p_id:f.dataset.id,p_reason:get('reason').trim()});}
  if(f.id==='settings'){await call('save_lending_settings',{p_data:{company:get('company').trim(),min_amount:num('min_amount'),max_amount:num('max_amount'),rate_bps:Math.round(num('rate')*100),max_months:num('max_months'),terms_ready:true,two_person:get('two_person')==='on'}});}
  if(f.id==='staff'){await call('manage_staff',{p_user:f.dataset.id,p_role:get('role'),p_active:get('active')==='on'});}
  if(f.id==='invite'){await api.invite(get('email').trim(),get('name').trim(),get('role'));}
  await sync(false);modal.close();draw();if(saved&&!syncError)receipt(saved.id);notice(demo?'Demo record updated.':syncError?'Saved to the database. Refresh is needed to show the updated records.':'Saved to the shared database.');
 }catch(err){if(box)box.textContent=err.message;else notice(err.message);}finally{busy=false;f.querySelectorAll('button').forEach(b=>b.disabled=false);}
});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
function startPolling(){clearInterval(poller);poller=setInterval(()=>{if(!document.hidden&&!modal.open&&!busy)sync();},20000);}
if(api.configured()&&!location.hostname.endsWith('github.io')){const invited=api.acceptInvite();if(api.restore()){await sync();startPolling();if(invited)passwordForm();}else login();}else login();
